feast-core:
  # feast-core.enabled -- Flag to install Feast Core
  enabled: true
  postgresql:
    # feast-core.postgresql.existingSecret -- Kubernetes secrets that contains the postgresql password
    existingSecret: feast-postgresql
  image:
    repository: gcr.io/kf-feast/feast-core
    tag: develop

feast-serving:
  # feast-online-serving.enabled -- Flag to install Feast Online Serving
  enabled: true
  image:
    repository: gcr.io/kf-feast/feast-serving
    tag: develop

feast-jupyter:
  # feast-jupyter.enabled -- Flag to install Feast Jupyter Notebook with SDK
  enabled: true
  image:
    repository: gcr.io/kf-feast/feast-jupyter
    tag: develop

feast-jobservice:
  # feast-jobservice.enabled -- Flag to install Feast Job Service
  image:
    repository: gcr.io/kf-feast/feast-jobservice
    tag: develop
  enabled: true

postgresql:
  # postgresql.enabled -- Flag to install Postgresql
  enabled: true
  # postgresql.existingSecret -- Kubernetes secrets that contains the postgresql password
  existingSecret: feast-postgresql

kafka:
  # kafka.enabled -- Flag to install Kafka
  enabled: true

redis:
  # redis.enabled -- Flag to install Redis
  enabled: true
  # redis.usePassword -- Disable redis password
  usePassword: false